[tool.black]                                                                                 
line-length = 120
exclude = "venv"

[tool.isort]
include_trailing_comma = true
multi_line_output=3

[tool.pylint]
    [tool.pylint.message_control]
    max-line-length = 120
